### ISSUE TITLE
Html setting ignored or not working

### ISSUE THREAD

**Issue by FAA-MichaelC** [NLog/NLog.MailKit#138]
I'm testing a .Net 6 console app with configuration from appsettings.json.  I have defined the following Mail target:

"mail": {
        "type": "Mail",
        "html": true,
        "body": "&lt;p font-family='Calibri Verdana'&gt;${level}&lt;br/&gt;${message}&lt;br/&gt;${exception}&lt;/p&gt;",
        "subject": "Error in NLog Demo",
        "smtpServer": "my.mailhost",
        "smtpAuthentication": "none",
        "from": "no-reply@faa.gov",
        "to": "my.address@faa.gov;"
      }

I am receiving email but the content is formatted as plain text, not html.  I'm not sure if this a problem for the NLog.MailKit package or the NLog.Extensions.Logging package, as the latter is responsible for parsing the settings file.

Also, on a related note, I initially used "Nlog Demo &lt;no-reply@faa.gov&gt;" for the value of "from" but it would blow up with a parsing error. (When I previewed this message, I saw the formatted version for the no-reply@faa.gov address, but my code has the markup escaped.)  Again, not sure where this error needs to be reported.

**Comment by FAA-MichaelC** [comment]
Never mind, I figured out the problem(s).  When using XML for configuration, the markup in the body and from address needs to be escaped, but not so when it's in JSON.  Didn't think this through before posting.

**Comment by 304NotModified** [comment]
I'm glad is has been resolved 👍
