### ISSUE TITLE
The nuget command failed - 403 - API key is invalid, has expired

### ISSUE THREAD

**Issue by snakefoot** [NLog/NLog.MailKit#140]
https://github.com/NLog/NLog.MailKit/runs/9591070707

**Comment by 304NotModified** [comment]
Thx, will try to fix this today

**Comment by 304NotModified** [comment]
@snakefoot 

Im waiting on this untill we're on one page for the dependency versions and the package version.

**Comment by 304NotModified** [comment]
@snakefoot I could add you to https://www.nuget.org/profiles/NLogLogging?

What's your username on nuget.org?

**Comment by snakefoot** [comment]
snakefoot :)

**Comment by snakefoot** [comment]
But not sure how to fix the NLog.MailKit-Azure-Deveops-pipeline. Like how all the others work with appveyor .

**Comment by snakefoot** [comment]
So now I'm a Collaborator for NLogLogging. What next ?

**Comment by 304NotModified** [comment]
I will try to updatec the key today. Maybe i could also make it easier for others.

**Comment by 304NotModified** [comment]
Fixed!

**Comment by snakefoot** [comment]
Thank you, much appreciated!
