### ISSUE TITLE
Error		Could not install package 'NLog.MailKit 1.1.1'.

### ISSUE THREAD

**Issue by ken-ee** [NLog/NLog.MailKit#16]
Error using Nuget to add package.  I already have nlog - working ok (barring sending mail via O365 or Gmail)

I wanted Nlog.mailkit to resolve email problem.  It wont install.

Error:

Could not install package 'NLog.MailKit 1.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			

Thanks for your time..!

**Comment by ken-ee** [comment]
Just for reference, would like to have nlog sending email via O365.  I see another functionality request for TLS was closed down a couple of months ago.

Add SecureSocketOption StartTls #13

**Comment by 304NotModified** [comment]
are you using VS 2017

**Comment by ken-ee** [comment]
Hi Julian.

Thanks for getting back to me.  Yes I am!

Is that a bad idea?! 8)

Cheers.

Ken.

On 10 Oct 2017, at 15:18, Julian Verdurmen <notifications@github.com<mailto:notifications@github.com>> wrote:


are you using VS 2017

**Comment by 304NotModified** [comment]
Do you need .NET 4.5 support? I think I can add it easily. Let me know!

**Comment by ken-ee** [comment]
Hi Julian.

There are a bunch of things I have used that are 4.5 on.  Even if it’s easy that would be still an amazing thing for you to do…

Kind Regards.

Ken.

**Comment by 304NotModified** [comment]
OK will start working on it. I haven't much time, but I hope it won't take much time :)

**Comment by 304NotModified** [comment]
fixed by https://github.com/NLog/NLog.MailKit/pull/17

Will be in 2.0. Now in the build queue!

Small binary change (not binary backwards compatible), s0 2.0

**Comment by 304NotModified** [comment]
live: https://www.nuget.org/packages/NLog.MailKit/2.0.0

**Comment by ken-ee** [comment]
Julian, you are a star.   Thank you very much.

Cheers.

Ken.

On 10 Oct 2017, at 21:05, Julian Verdurmen <notifications@github.com<mailto:notifications@github.com>> wrote:


live: https://www.nuget.org/packages/NLog.MailKit/2.0.0
