### ISSUE TITLE
Authentication Failure

### ISSUE THREAD

**Issue by Apocatastasis** [NLog/NLog.MailKit#23]
I have the following configuration:
` <target xsi:type="Mail"
          name="mail"
          smtpServer="xx.xx.xx.xx"
          smtpPort="25"
          enableSsl="false"
          smtpAuthentication="Basic"
          smtpUserName="${mailUser}"
          smtpPassword="${mailPwd}"
          from="${mailUser}"
          to="${mailDistributionList}"
          subject="Sample subject"
          addNewLines="true"
          skipCertificateValidation="true" />   `
My server doesn't support SSL, altough in the full framework version of NLog works well.  I don't know if this is a bug in the mailKit implementation or is the case that NLog for Core don't support variable substitution .

**Comment by Apocatastasis** [comment]
I found my asnwer [here](https://github.com/NLog/NLog/issues/2286)

**Comment by 304NotModified** [comment]
:+1:
