### ISSUE TITLE
Move to NLog 4.5

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.MailKit#24]
Update dependencies

see https://github.com/NLog/NLog.Extensions.Logging/issues/164

**Comment by 304NotModified** [comment]
fixed by #25

**Comment by 304NotModified** [comment]
@emarchal78 NLog.Mailkit 2.1.1 is in the build queue!

**Comment by 304NotModified** [comment]
It's online!

https://www.nuget.org/packages/NLog.MailKit/2.1.1

**Comment by emarchal78** [comment]
Great thanks Julian

2017-12-20 18:34 GMT+01:00 Julian Verdurmen <notifications@github.com>:
