### ISSUE TITLE
Asp.Net core 1.1 - request parameters are empty in log [url/querystring and etc..,]

### ISSUE THREAD

**Issue by SowmiyaVel** [NLog/NLog.MailKit#31]
Hi ,

I started using Nlog for logging in Asp.Netcore1.1.
I added Nuget Package
NLog.Extensions.Logging(1.2.1)
NLog.Web.AspNetCore(4.6.0)
NLog.MailKit(3.0.0)

In email logs, I am trying to print Request url, environment, request query string , windows-identity.
But it fails, all are empty.

Could you help me in this. 
am I missing any other packages.

Thanks in advance.

**Comment by 304NotModified** [comment]
The request url etc is only available when there is a httpcontext. Is that available in your project? (e.g. read asp.net (core))

**Comment by SowmiyaVel** [comment]
yes, it is available . do i need to get it inside nlog.config??
And can u give me the syntax for using those request renderers.
As of now i am using ${aspnet-request-url}

**Comment by SowmiyaVel** [comment]
Sorry, I missed this part in Nlog configuring. Thats the cause of the issue.
![image](https://user-images.githubusercontent.com/43207541/45427926-ba91ed80-b6bd-11e8-9f34-117393bb23c0.png)

**Comment by 304NotModified** [comment]
yes it's a bit hidden. In ASP.NET Core 2 integration that could be solved better. (read we do configure the hpptContextAccessor when needed)
