### ISSUE TITLE
HTML in Nlog email

### ISSUE THREAD

**Issue by SowmiyaVel** [NLog/NLog.MailKit#32]
I am not able to implement HTML in nlog layout, and i dont find any example.

Do I really need to escape html characters to achieve this ??

**Comment by 304NotModified** [comment]
in the XML you need to escape the HTML, but could could use CDATA.

See https://stackoverflow.com/questions/4412395/is-it-possible-to-insert-html-content-in-xml-document

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, please let us know!
