### ISSUE TITLE
Fix obsolete 

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.MailKit#43]
Fix this warning:

> warning CS0672: Member 'MailTarget.Write(AsyncLogEventInfo[])' overrides obsolete member 'Target.Write(AsyncLogEventInfo[])'. Add the Obsolete attribute to 'MailTarget.Write(AsyncLogEventInfo[])'

**Comment by sooraj19** [comment]
@304NotModified : Can you please take a look at my PR.. Thanks..

**Comment by 304NotModified** [comment]
Merged, thanks!
