### ISSUE TITLE
Possibility to encrypt/obfuscate password in NLog.config file

### ISSUE THREAD

**Issue by SylwesterZarebski** [NLog/NLog.MailKit#57]
I would like to have possibility to encrypt or obfuscate password in NLog.config file. Now, file is easily available for third persons using application, thus password to SMTP server is available also.

Maybe there is another way to remove/hide password from config file?

**Comment by 304NotModified** [comment]
.NET Framework or .NET Core?

- For .NET Framework there is http://davidgiard.com/2012/06/05/EncryptingAndDecryptingApplicationConfigSections.aspx
- For .NET Core there is https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-2.2&tabs=windows

Not sure if we need to change something here to support that

**Comment by SylwesterZarebski** [comment]
But this is about NLog.config, not app.config.
Or it is possible to embed NLog.config in app.config file?

**Comment by 304NotModified** [comment]
Yes it is :)

See https://github.com/NLog/NLog/wiki/Configuration-file#file-layout

**Comment by SylwesterZarebski** [comment]
I was not aware of this possibility. I'll check this, thanks.
