### ISSUE TITLE
Mail / Mailkit - Priority ?

### ISSUE THREAD

**Issue by BeJoNe** [NLog/NLog.MailKit#77]
We are using the mail priority in our nlog configurations.
In the [Wiki-Mail-target](https://github.com/nlog/nlog/wiki/Mail-target ) there is no description about the "priority" of the mail message yet.
It worked so far with with priority set to one of "low,normal,high" according to
[MailTarget.cs](https://github.com/NLog/NLog/blob/dev/src/NLog/Targets/MailTarget.cs)
`Line 652: InternalLogger.Warn("MailTarget(Name={0}): Could not convert '{1}' to MailPriority, valid values are Low, Normal and High. Using normal priority as fallback.", Name, renderedPriority);
`

As we switched to NLog.MailKit I saw this line in the source:
[MailTarget.cs](https://github.com/NLog/NLog.MailKit/blob/master/src/NLog.MailKit/MailTarget.cs)
`Line 533: InternalLogger.Warn("Could not convert '{0}' to MessagePriority, valid values are NonUrgent, Normal and Urgent. Using normal priority as fallback.");
`
So I was wondering what the attribute values should be?
Members of  System.Messaging.MessagePriority: Low,Normal,High
or like in the warning: NonUrgent,Normal,Urgent

Could you please clarify?

**Comment by BeJoNe** [comment]
Tested one more:
When NLog.MailKit is absent, the working values are : Low,Normal,High
With NLog.MailKit only these : NonUrgent,Normal,Urgent

To me, this IS a breaking change (although it is still not documented :) )

**Comment by 304NotModified** [comment]
> To me, this IS a breaking change (although it is still not documented :) )

Agree! I think we should document it. Could you please edit https://github.com/nlog/nlog/wiki/Mail-target?

**Comment by BeJoNe** [comment]
Update wiki, no problem.
Do you change the MailKit parser to also be backward compatible with "Low, Normal and High"?

**Comment by 304NotModified** [comment]
That's not the plan for now. There are some minor differences, but I think that's fine when documented

**Comment by 304NotModified** [comment]
I think i'm fine with a PR that will fix this (so converting also   Low, Normal and High)

**Comment by 304NotModified** [comment]
Thanks for reporting, this is fixed in 3.2
